logger:
  - class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: ${project_name}
      name: run-${path_seg:${.dir},-1}
      id: "???"  # needs to be replaced
      save_dir: ${trainer.default_root_dir}
      resume: allow
      offline: true