model:
  class_path: src.models.ielt.IELT
  init_args:
    reinit_final_blocks: True
    warmup_epochs: 10
    drop_rate: 0.7
    base_conf:
      base_lr: 1e-2
      finetune_lr_scale: 0.1
      weight_decay: 1e-5
    model_conf:
      model_name: vit_base_patch16_224.augreg_in1k
      pretrained: true
      num_classes: ${num_labels:${data.class_path}}
      model_kw:
        img_size: ${data.init_args.size}
        proj_drop_rate: 0.1
