model:
  class_path: src.models.pim.PIM
  init_args:
    img_size: 448
    num_selects:
      layer1: 2048
      layer2: 512
      layer3: 128
      layer4: 32
    base_conf:
      base_lr: 1e-2
      finetune_lr_scale: 0.1
      weight_decay: 1e-5
    model_conf:
      model_name: resnet50
      pretrained: ${oc.env:DATADIR}/resnet50_torchvision_v2.pth
      num_classes: ${num_labels:${data.class_path}}