model:
  class_path: src.models.pmg.PMG
  init_args:
    base_conf:
      optimizer_name: SGD
      base_lr: 1e-2
      finetune_lr_scale: 0.1
    model_conf:
      model_name: resnet50
      pretrained: ${oc.env:DATADIR}/resnet50_torchvision_v2.pth
      num_classes: ${num_labels:${data.class_path}}