model:
  class_path: src.models.pmg.PMG
  init_args:
    model_conf:
      model_name: resnet50
      pretrained: ${oc.env:DATADIR}/resnet50_miil_21k.pth
      num_classes: ${num_labels:${data.class_path}}