model:
  class_path: src.models.base.ImageClassifier
  init_args:
    base_conf:
      base_lr: 1e-2
      finetune_lr_scale: 0.02
    model_conf:
      model_name: vit_base_patch16_224_miil.in21k
      pretrained: true
      num_classes: ${num_labels:${data.class_path}}
      model_kw:
        img_size: ${data.init_args.size}
        global_pool: avg