model:
  class_path: src.models.wsdan.WSDAN
  init_args:
    base_conf:
      base_lr: 1e-3
      finetune_lr_scale: 1.0
    model_conf:
      model_name: resnet50
      pretrained: ${oc.env:DATADIR}/resnet50_torchvision_v2.pth
      num_classes: ${num_labels:${data.class_path}}